/*
 * Apart-Deal API Contracts
 *
 * Apart-Deal API Contracts
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SignUpResponse struct {
	Token string `json:"token"`
}
