/*
 * Apart-Deal API Contracts
 *
 * Apart-Deal API Contracts
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SignUp struct {
	Name string `json:"name"`

	Email string `json:"email"`

	Password string `json:"password"`
}
