/*
 * Apart-Deal API Contracts
 *
 * Apart-Deal API Contracts
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type AuthToken struct {
	Token string `json:"token"`

	RefreshToken string `json:"refresh_token"`

	ExpiresAt time.Time `json:"expires_at,omitempty"`
}
