openapi: "3.0.0"

info:
  title: Apart-Deal API Contracts
  description: Apart-Deal API Contracts
  version: 0.0.1

paths: {}

components:
  schemas:

    SignUp:
      type: object
      required: [name, email, password]
      properties:
        name:
          type: string
          minLength: 2
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 5

    SignUpResponse:
      type: object
      required: [token]
      properties:
        token:
          type: string

    SignIn:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 5

    SignedIn:
      type: object
      required: [token]
      properties:
        token:
          type: string

    ConfirmSignUp:
      type: object
      required: [code, token]
      properties:
        code:
          type: string
        token:
          type: string
